<a href="https://colab.research.google.com/github/marinamangia/br-python-challenges/blob/master/Desafio_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Desafio 10

Dada uma lista, divida-a em 3 partes iguais e reverta a ordem de cada lista.

**Exemplo:** 

Entrada: \
sampleList = [11, 45, 8, 23, 14, 12, 78, 45, 89]

Saída: \
Parte 1 [8, 45, 11] \
Parte 2 [12, 14, 23] \
Parte 3 [89, 45, 78] 

In [5]:
import numpy as np

In [12]:
sampleList = [11, 45, 8, 23, 14, 12, 78, 45, 89]

In [15]:
splits = np.array_split(sampleList, 3)
for array in splits:
  print(array[::-1])

[ 8 45 11]
[12 14 23]
[89 45 78]
